name = "accordingly-coordinator"
main = "src/index.ts"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "accordingly.me", custom_domain = true }
]

[observability]
enabled = true

[dev]
port = 8000

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[vars]
ENVIRONMENT = "development"

[[d1_databases]]
binding       = "DB"
database_name = "accordingly"
database_id   = "deb07094-176a-466f-ac35-5d4c9594f686"
migrations_dir = "migrations"
